ADD: SignUp page and routes to pages
coronado03/Speculo pull request #10
Opened 2024-10-19 23:07 UTC by abbosjon99

2024-10-19 23:56 UTC, coronado03 requested changes
LGTM!  just a few comments

2024-10-19 23:56 UTC, coronado03 commented on frontend/src/app/signin/page.tsx
> +    <main className="sign-background">
Remove div and put css in main

2024-10-19 23:56 UTC, coronado03 commented on frontend/src/app/signup/page.tsx
> +    <main className="sign-background">
same here

2024-10-19 23:56 UTC, coronado03 commented on frontend/src/components/auth/signin/signin.tsx
> +          <a
https://nextjs.org/docs/pages/api-reference/components/link

use next link instead for performance

2024-10-19 23:56 UTC, coronado03 commented on frontend/src/components/auth/signup/signup.tsx
> +          <a
Next Link here too

2024-10-19 23:56 UTC, coronado03 commented on frontend/src/app/page.tsx
> +      <div className="w-screen flex justify-center h-screen items-center gap-4">
remove gap-4

2024-10-19 23:56 UTC, coronado03 commented on frontend/src/app/signin/page.tsx
> +      <div className="w-screen flex justify-center h-screen items-center gap-4">
remove gap-4

2024-10-20 00:00 UTC, abbosjon99 commented on frontend/src/app/signin/page.tsx
> +    <main className="sign-background">
✅

2024-10-20 00:00 UTC, abbosjon99 commented on frontend/src/app/signup/page.tsx
> +    <main className="sign-background">
✅

2024-10-20 00:01 UTC, abbosjon99 commented on frontend/src/app/page.tsx
> +      <div className="w-screen flex justify-center h-screen items-center gap-4">
✅

2024-10-20 00:01 UTC, abbosjon99 commented on frontend/src/app/signin/page.tsx
> +      <div className="w-screen flex justify-center h-screen items-center gap-4">
✅

2024-10-20 00:04 UTC, abbosjon99 commented on frontend/src/components/auth/signin/signin.tsx
> +          <a
✅

2024-10-20 00:04 UTC, abbosjon99 commented on frontend/src/components/auth/signup/signup.tsx
> +          <a
✅

2024-10-20 00:07 UTC, merged